In [1]:
import numpy as np
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a[0:3,1:3])


[[ 2  3]
 [ 6  7]
 [10 11]]


In [19]:
a1=np.array([
    [[1,2,3,4],[5,6,7,8],[9,10,11,12]],
    [[13,14,15,16],[17,18,19,20],[21,22,23,24]],
    [[25,25,27,28],[29,30,31,32],[33,34,35,36]]
])
print(a1[0:1])
    

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]


In [20]:
a2=np.array(["Hello",10,4.5])
print(a2.dtype)

<U32


In [23]:
a3=np.array([1,2,3,4],dtype="f")
print(a3,a3.dtype)            


[1. 2. 3. 4.] float32


In [24]:
a=np.array([1,2,3,0,4],dtype="bool")
print(a,a.dtype)

[ True  True  True False  True] bool


In [26]:
a=np.array([1.,2.,3.,4.])
b=a.astype("i")
print(b,b.dtype)

[1 2 3 4] int32


# Slicing

In [3]:
a=np.array([113,15,19,20,50,100,200])
print(a[0:3])

[113  15  19]


In [6]:
a=np.array([  [1,2,3,4,5],  [6,7,8,9,10] ]) 
print(a[1,1:4]) # 0 index--1,2,3,4,5   and 1 index----6,7,8,9,10  

[7 8 9]


In [15]:
#print(a[0:2,1:4]) # 0:2---0,1 block and 1:4--2,3,4 and 7,8,9
print(a[0:2,2])

[3 8]


In [20]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
# output :[[2,3],
#          [6,7],
#         [10,11]
print(a[0:,1:3]) 

[[ 2  3]
 [ 6  7]
 [10 11]]


In [28]:
a=np.array([
    [[1,2,3,4],[5,6,7,8],[9,10,11,12]], # 0--0,1,2
    [[13,14,15,16],[17,18,19,20],[21,22,23,24]], #1--0,1,2
    [[25,26,27,28],[29,30,31,32],[33,34,35,36]] #2--0,1,2
])  


In [ ]:
# output [[1 2 3 4 ],
#         [5,6,7,8]
#      [9,10,11,12]]

In [31]:
#print(a[0,:])
print(a[0,1,2]) # [0,1,2] her 2 value----is 1 box and 2 element


7


In [33]:
# copy: copy of the object/array changes made in copy will not reflect in original
# view: shares the data     changes made in view will in original
a=np.array([1,2,3,4])
b=a.copy()
b
b[1]=100 #[1,100,3,4]

array([  1, 100,   3,   4])

In [40]:
a=np.array([1,2,3,4])
b=a.view()
b
b[1]=100
print(b)
print(a)

[  1 100   3   4]
[  1 100   3   4]


In [41]:
# reshape
a=np.array([[1,2,3,4,5],[6,7,8,9,10]])
a=a.reshape(-1)#convert into 1D
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# Search

In [47]:
a=np.array([1,2,3,4,5,6]) #[2,4,6]
x=np.where(a%2==0)
print(a[x])

[2 4 6]


In [48]:
# odd find out

# Sort the Array

In [49]:
a=np.array([18,19,20,22,89,60])
print(np.sort(a))

[18 19 20 22 60 89]


In [51]:
#decsending Sort
np.sort(a)[::-1]

array([89, 60, 22, 20, 19, 18])

In [55]:
a='hello'
a[::-1]

'olleh'