# Linspace

In [2]:
import numpy as np

In [4]:
a=np.linspace(1,5,6)
a

array([1. , 1.8, 2.6, 3.4, 4.2, 5. ])

In [5]:
a=np.linspace(1,5,6,retstep=True) #retstep=Gap
a

(array([1. , 1.8, 2.6, 3.4, 4.2, 5. ]), np.float64(0.8))

In [6]:
a=np.linspace(1,5,6,retstep=True,endpoint=False)
a

(array([1.        , 1.66666667, 2.33333333, 3.        , 3.66666667,
        4.33333333]),
 np.float64(0.6666666666666666))

# Diagonal Matrics

In [7]:
a=np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [8]:
a=np.identity(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
a=np.diag([1,4,3])
a

array([[1, 0, 0],
       [0, 4, 0],
       [0, 0, 3]])

# Join array

In [17]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
#c=np.concatenate((a,b)) #single line 1D
#print(np.stack((a,b))) #up down stack form 2D
print(np.hstack((a,b))) #output like 1D

[1 2 3 4 5 6 7 8]


In [21]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
print(np.concatenate((a,b),axis=0))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [22]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
print(np.concatenate((a,b),axis=1))

[[1 2 5 6]
 [3 4 7 8]]


In [23]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
print(np.hstack((a,b)))

[[1 2 5 6]
 [3 4 7 8]]


In [24]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
print(np.vstack((a,b)))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [29]:
a=np.array([[[1,2],[3,4]]])
b=np.array([[[5,6],[7,8]]])
print(np.concatenate((a,b),axis=0))

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [30]:
a=np.array([[[1,2],[3,4]]])
b=np.array([[[5,6],[7,8]]])
print(np.dstack((a,b)))

[[[1 2 5 6]
  [3 4 7 8]]]


# Insert Delete Append

In [31]:
a=np.array([1,2,4,5]) #2nd index---3value
a=np.insert(a,2,3) #a=variable,2=index,3=value
a

array([1, 2, 3, 4, 5])

In [32]:
a=np.array([1,2,4,5])
a=np.append(a,6)  #adds the value in last
a

array([1, 2, 4, 5, 6])

In [34]:
a=np.array([1,2,4,5])
a=np.delete(a,2)
a

array([1, 2, 5])

# Random 

In [37]:
print(np.random.randint(1,30))

22


In [39]:
print(np.random.randint(1,30,(2,3))) #same print(np.random.randint((1,30(2,3,2)))---3D

[[ 5  5  7]
 [14  6 21]]


In [40]:
print(np.random.rand()) # 0-1

0.6220643885247128


In [41]:
print(np.random.uniform(1,30)) # floatno btw 1---30

29.059729016813442


In [42]:
print(np.random.uniform(1,30,(2,3)))

[[21.93645214 21.09357089  7.66564077]
 [ 4.23523299 28.25534606 10.01825251]]


In [48]:
a=np.array([10,20,30,40,50])
print(np.random.choice(a))
print(np.random.choice(a,3))
print(np.random.choice(a,(2,3)))

20
[20 30 30]
[[50 40 30]
 [20 50 50]]
