In [9]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8])
a=a.reshape(2,2,2)
print(a)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [10]:
a=np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
a=a.reshape(2,3,2)
print(a)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [12]:
a=np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])
a=a.reshape(4,3)
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [13]:
a=np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])
a=a.reshape(12)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [14]:
a=np.array([[1,2,3,4],[5,6,7,8]])
a=a.reshape(8)
print(a)

[1 2 3 4 5 6 7 8]


In [23]:
a=np.array([1,2,3,4,5,6])
for i in a:
    print(i)


1
2
3
4
5
6


In [30]:
a=np.array([[1,2,3,4],[5,6,7,8]])
for i in a:
    for j in i:
        print(j)

1
2
3
4
5
6
7
8
